# Site settings
title: Vagner Barbosa
email: contato@vagnerbarbosa.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://vagnerbarbosa.com" # the base hostname & protocol for your site
twitter_username: myselfvagner
github_username:  vagnerbarbosa

# Build settings
markdown: kramdown

port: 8080


