# Site settings
title: Vagner Barbosa
description: Vagner Barbosa Resume Minimal Page
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Vagner Barbosa
user_description: In the IT since 2012. Software Developer Analyst in search of a professional environment that is more humanized, inclusive and responsible! :)
user_title: Software Developer Analyst
email: contato@vagnerbarbosa.com
 #twitter_username: lorem_ipsum
 #github_username:  lorem_ipsum
 #gplus_username:  lorem_ipsum
 #linkin_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
