# Site settings
title: Vagner Barbosa + FullStack Developer
email: contato@vagnerbarbosa.com
description: "l"
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://vagnerbarbosa.com" # the base hostname & protocol for your site
twitter_username: myselfvagner
github_username:  vagnerbarbosa

# Build settings
markdown: kramdown

port: 8080


